### ISSUE TITLE
Galactic-Craft Oxygen

### ISSUE THREAD

**Issue by JensenButton9** [SleepingTea98/Colony-Modpack#10]
I have an issue with Galatic Craft on my server where the Oxygen bubble distributor and oxygen sealer will create a sealed environment but when I take my oxygen gear off it will tell me there is no oxygen. This problem is limited to multiplayer and not present on single player as on single player I tested and this issue was not arising. I'm unsure about the causality of this issue.
![2019-04-07_13 59 50](https://user-images.githubusercontent.com/49365963/55684041-99853880-593e-11e9-973c-b30173041050.png)
![2019-04-07_14 00 00](https://user-images.githubusercontent.com/49365963/55684042-99853880-593e-11e9-96b6-7cd947458391.png)

**Comment by SleepingTea98** [comment]
This is a bug with the mod, please take this up with them. Sorry!

**Comment by JensenButton9** [comment]
Ok, thank you, probably fixed in newer versions then.
