### ISSUE TITLE
I keep crashing upon launching pack

### ISSUE THREAD

**Issue by viper7804** [SleepingTea98/Colony-Modpack#11]
And yes I Have over 3GB of ram allocated

**Comment by SleepingTea98** [comment]
Please send us your crash log

**Comment by viper7804** [comment]
Problem with that it didn’t give me one but I think I may have fixed it by fluctuating with my ram and my game booster

**Comment by SleepingTea98** [comment]
Closed due to modpack updating to 1.12.2
