### ISSUE TITLE
(Not really a bug, but here it is) How to lose a lightsaber...

### ISSUE THREAD

**Issue by XtmelihuX** [SleepingTea98/Colony-Modpack#12]
I was messing around with the throwing skill in Advanced Lightsabers, then I threw it at my nether portal, then it dissapeared, and then the server crashed for me. Rather, the server closed... I couldn't join for 20 min. then I lost my lightsaber due to despawn.(I think.) RIP.

**Comment by XtmelihuX** [comment]
If its possible... maybe getting my lightsaber back? It was a cyan normal and graflex hilt.

**Comment by SleepingTea98** [comment]
Closed due to modpack updating to 1.12.2
