### ISSUE TITLE
Missing Ores Project Red

### ISSUE THREAD

**Issue by JensenButton9** [SleepingTea98/Colony-Modpack#14]
The ores for Project Red are missing from the mod pack making some project red machines unmakable.
![Furnace Example](https://user-images.githubusercontent.com/49365963/56751787-c62eb200-677e-11e9-8d01-813345befe34.JPG)
![2019-04-25_17 23 11](https://user-images.githubusercontent.com/49365963/56751882-f6765080-677e-11e9-8dee-3c586326aead.png)

**Comment by SleepingTea98** [comment]
Closed due to modpack updating to 1.12.2
