### ISSUE TITLE
banned block placing glitch & crafting glitch

### ISSUE THREAD

**Issue by epicsquid610** [SleepingTea98/Colony-Modpack#15]
There is a glitch where if you right click with any tconstruct pickax with a banned block to the right of the tool,it bypasses the banned item plugin and allows you to place and in turn use the block.
The other glitch is where if you craft a banned item in an ME system and shift it out it will place it in your inventory.

**Comment by SleepingTea98** [comment]
Closed due to modpack updating to 1.12.2
