### ISSUE TITLE
Mod rejections [FMLMod:OpenComputers{1.7.4.1265}] on connecting to a private server.

### ISSUE THREAD

**Issue by Superfish1000** [SleepingTea98/Colony-Modpack#2]
After the update to 3.3.2 it is impossible to connect to a private server because the OpenComputers mod doesn't match.

Tested with a fresh server and launcher install.

**Comment by SleepingTea98** [comment]
Hello,

This isn't a bug. The server files haven't yet been updated.

You can update the server yourself if you need them now. Take the OpenComputers mod from the new update and replace the one in your server files.

If you need any help with this, please message our staff team!
