### ISSUE TITLE
Overlapping recipe (Iron Frame and Iron Gear)

### ISSUE THREAD

**Issue by Cosmobob1** [SleepingTea98/Colony-Modpack#26]
I was trying to craft an iron frame from the advanced generators mod but is recipe is the same as an iron gear. This made it so that you can only craft the iron gears instead of iron frames which causes you to not be able to do anything with the advanced generators mod which i really like using.

**Comment by Zeno-ZX** [comment]
You can trade 1 Iron Gear for 2 Iron Frames at the Admin Shop.
