### ISSUE TITLE
cables problem

### ISSUE THREAD

**Issue by Skettlu** [SleepingTea98/Colony-Modpack#5]
when you have a thermal dynamic wrench if you shift right click you can pick up cables,pipes and ect even in claims

**Comment by SleepingTea98** [comment]
Thanks, we're looking into the issue

**Comment by filtses** [comment]
Yeah now you can actually take down universal cablel with a wrench not only ae2 cables.I think the last update made this type of problem.

**Comment by SleepingTea98** [comment]
Closed due to modpack updating to 1.12.2
